// Minimal flat-icon glyph data for the 44 quiz symbols. viewBox is always "0 0 24 24".
// Regenerated by scripts/rebuild-icons.mjs (Lucide CDN + handcrafted symbolic glyphs).

import hammerSickleUrl from "../../imports/hammer_sickle_circle.svg";
import omSymbolUrl from "../../imports/om_symbol.svg";
import prideFlagUrl from "../../imports/pride_flag.svg";
import starCrescentUrl from "../../imports/star_crescent.svg";

export type IconShape = {
  t: string;
  fill?: string;
  stroke?: string;
  sw?: number;
  transform?: string;
  cx?: number;
  cy?: number;
  r?: number;
  rx?: number;
  ry?: number;
  x?: number;
  y?: number;
  w?: number;
  h?: number;
  d?: string;
  points?: string;
  x1?: number;
  y1?: number;
  x2?: number;
  y2?: number;
  key?: string | number;
};

export type IconSymbol = {
  id: number;
  name: string;
  shapes: IconShape[];
  /** Optional full SVG asset (used instead of shapes when set). */
  assetUrl?: string;
};

export const SYMBOLS: IconSymbol[] = [
  { id: 1, name: "Hammer and sickle", assetUrl: hammerSickleUrl, shapes: [] },
  { id: 2, name: "Red star", shapes: [
    { t: "polygon", points: "12,2 14.469,8.602 21.511,8.91 15.994,13.298 17.878,20.09 12,16.2 6.122,20.09 8.006,13.298 2.489,8.91 9.531,8.602", fill: "#dc2626" },
  ] },
  { id: 3, name: "Anarchist circle-A", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 10.2, stroke: "#111827", sw: 1.9, fill: "none" },
    { t: "line", x1: 12, y1: 5.2, x2: 6.2, y2: 18.5, stroke: "#111827", sw: 1.9 },
    { t: "line", x1: 12, y1: 5.2, x2: 17.8, y2: 18.5, stroke: "#111827", sw: 1.9 },
    { t: "line", x1: 8.2, y1: 14.2, x2: 15.8, y2: 14.2, stroke: "#111827", sw: 1.9 },
  ] },
  { id: 4, name: "Raised fist", shapes: [
    { t: "rect", x: 9.5, y: 15, w: 5, h: 5.5, rx: 1, fill: "#c68958" },
    { t: "path", d: "M7 14.5V8.2a2 2 0 0 1 2-2h.8V14.5z", fill: "#c68958" },
    { t: "path", d: "M9.8 6.2h2.2V14.5H9.8z", fill: "#b67848" },
    { t: "path", d: "M12 5.5h2.2V14.5H12z", fill: "#c68958" },
    { t: "path", d: "M14.2 6.2h2.2a1.5 1.5 0 0 1 1.5 1.5V14.5h-3.7z", fill: "#b67848" },
    { t: "path", d: "M6.5 10.5c-1.8.2-2.8 1.6-2.8 3.2 0 1.4 1 2.5 2.6 2.5H9.5V12c0-.9.4-1.5 1-1.5", fill: "#c68958" },
    { t: "rect", x: 8.5, y: 19.5, w: 7, h: 1.8, rx: 0.4, fill: "#8a5a35" },
  ] },
  { id: 5, name: "Scales of justice", shapes: [
    { t: "path", d: "m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M7 21h10", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M12 3v18", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2", fill: "none", stroke: "#6b7280", sw: 1.75 },
  ] },
  { id: 6, name: "Ballot box with slotted paper", shapes: [
    { t: "path", d: "m9 12 2 2 4-4", fill: "none", stroke: "#374151", sw: 1.75 },
    { t: "path", d: "M5 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v12H5V7Z", fill: "none", stroke: "#374151", sw: 1.75 },
    { t: "path", d: "M22 19H2", fill: "none", stroke: "#374151", sw: 1.75 },
  ] },
  { id: 7, name: "Dove carrying an olive branch", shapes: [
    { t: "ellipse", cx: 11.5, cy: 12, rx: 6.2, ry: 3.8, fill: "#f3f4f6" },
    { t: "path", d: "M6.5 11.5c-2.5.2-4 2-4.5 3.8 1.6-.2 3.2-.8 4.2-1.8z", fill: "#e5e7eb" },
    { t: "polygon", points: "17.2,11.2 21.5,10.2 17.2,9.4", fill: "#f59e0b" },
    { t: "circle", cx: 15.8, cy: 10.6, r: 0.55, fill: "#111827" },
    { t: "path", d: "M4.2 15.2c-1.5 1.2-2.4 2.8-2.6 4.4", stroke: "#4d7c0f", sw: 1.3, fill: "none" },
    { t: "ellipse", cx: 1.8, cy: 19.6, rx: 1.3, ry: 0.8, fill: "#65a30d" },
    { t: "ellipse", cx: 3.2, cy: 18.4, rx: 1.1, ry: 0.7, fill: "#65a30d" },
  ] },
  { id: 8, name: "Wavy flag silhouette", shapes: [
    { t: "path", d: "M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z", fill: "none", stroke: "#3b82f6", sw: 1.75 },
    { t: "line", x1: 4, y1: 22, x2: 4, y2: 15, fill: "none", stroke: "#3b82f6", sw: 1.75 },
  ] },
  { id: 9, name: "Eagle (national emblem style)", shapes: [
    { t: "polygon", points: "12,4.5 13.2,7.5 10.8,7.5", fill: "#78350f" },
    { t: "circle", cx: 12, cy: 8.2, r: 2, fill: "#92400e" },
    { t: "polygon", points: "12,9.5 2.5,13.5 6.5,12.2 8.5,14.5 10.5,12.8 12,20 13.5,12.8 15.5,14.5 17.5,12.2 21.5,13.5", fill: "#78350f" },
    { t: "polygon", points: "11.2,19.2 12,22 12.8,19.2", fill: "#f59e0b" },
  ] },
  { id: 10, name: "Crown", shapes: [
    { t: "path", d: "M11.562 3.266a.5.5 0 0 1 .876 0L15.39 8.87a1 1 0 0 0 1.516.294L21.183 5.5a.5.5 0 0 1 .798.519l-2.834 10.246a1 1 0 0 1-.956.734H5.81a1 1 0 0 1-.957-.734L2.02 6.02a.5.5 0 0 1 .798-.519l4.276 3.664a1 1 0 0 0 1.516-.294z", fill: "none", stroke: "#eab308", sw: 1.75 },
    { t: "path", d: "M5 21h14", fill: "none", stroke: "#eab308", sw: 1.75 },
  ] },
  { id: 11, name: "Gavel", shapes: [
    { t: "path", d: "m14.5 12.5-8 8a2.119 2.119 0 1 1-3-3l8-8", fill: "none", stroke: "#6b4423", sw: 1.75 },
    { t: "path", d: "m16 16 6-6", fill: "none", stroke: "#6b4423", sw: 1.75 },
    { t: "path", d: "m8 8 6-6", fill: "none", stroke: "#6b4423", sw: 1.75 },
    { t: "path", d: "m9 7 8 8", fill: "none", stroke: "#6b4423", sw: 1.75 },
    { t: "path", d: "m21 11-8-8", fill: "none", stroke: "#6b4423", sw: 1.75 },
  ] },
  { id: 12, name: "Classical/capitol building silhouette", shapes: [
    { t: "line", x1: 3, y1: 22, x2: 21, y2: 22, fill: "none", stroke: "#9ca3af", sw: 1.75 },
    { t: "line", x1: 6, y1: 18, x2: 6, y2: 11, fill: "none", stroke: "#9ca3af", sw: 1.75 },
    { t: "line", x1: 10, y1: 18, x2: 10, y2: 11, fill: "none", stroke: "#9ca3af", sw: 1.75 },
    { t: "line", x1: 14, y1: 18, x2: 14, y2: 11, fill: "none", stroke: "#9ca3af", sw: 1.75 },
    { t: "line", x1: 18, y1: 18, x2: 18, y2: 11, fill: "none", stroke: "#9ca3af", sw: 1.75 },
    { t: "polygon", points: "12 2 20 7 4 7", fill: "none", stroke: "#9ca3af", sw: 1.75 },
  ] },
  { id: 13, name: "Circle of stars (EU-style)", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 11, fill: "#1d4ed8" },
    { t: "polygon", points: "12,3.25 12.382,4.274 13.474,4.321 12.618,5.001 12.911,6.054 12,5.45 11.089,6.054 11.382,5.001 10.526,4.321 11.618,4.274", fill: "#facc15" },
    { t: "polygon", points: "15.6,4.215 15.982,5.239 17.074,5.286 16.218,5.965 16.511,7.019 15.6,6.415 14.689,7.019 14.982,5.965 14.126,5.286 15.218,5.239", fill: "#facc15" },
    { t: "polygon", points: "18.235,6.85 18.617,7.874 19.71,7.921 18.854,8.601 19.146,9.654 18.235,9.05 17.324,9.654 17.617,8.601 16.761,7.921 17.853,7.874", fill: "#facc15" },
    { t: "polygon", points: "19.2,10.45 19.582,11.474 20.674,11.521 19.818,12.201 20.111,13.254 19.2,12.65 18.289,13.254 18.582,12.201 17.726,11.521 18.818,11.474", fill: "#facc15" },
    { t: "polygon", points: "18.235,14.05 18.617,15.074 19.71,15.121 18.854,15.801 19.146,16.854 18.235,16.25 17.324,16.854 17.617,15.801 16.761,15.121 17.853,15.074", fill: "#facc15" },
    { t: "polygon", points: "15.6,16.685 15.982,17.71 17.074,17.756 16.218,18.436 16.511,19.489 15.6,18.885 14.689,19.489 14.982,18.436 14.126,17.756 15.218,17.71", fill: "#facc15" },
    { t: "polygon", points: "12,17.65 12.382,18.674 13.474,18.721 12.618,19.401 12.911,20.454 12,19.85 11.089,20.454 11.382,19.401 10.526,18.721 11.618,18.674", fill: "#facc15" },
    { t: "polygon", points: "8.4,16.685 8.782,17.71 9.874,17.756 9.018,18.436 9.311,19.489 8.4,18.885 7.489,19.489 7.782,18.436 6.926,17.756 8.018,17.71", fill: "#facc15" },
    { t: "polygon", points: "5.765,14.05 6.147,15.074 7.239,15.121 6.383,15.801 6.676,16.854 5.765,16.25 4.854,16.854 5.146,15.801 4.29,15.121 5.383,15.074", fill: "#facc15" },
    { t: "polygon", points: "4.8,10.45 5.182,11.474 6.274,11.521 5.418,12.201 5.711,13.254 4.8,12.65 3.889,13.254 4.182,12.201 3.326,11.521 4.418,11.474", fill: "#facc15" },
    { t: "polygon", points: "5.765,6.85 6.147,7.874 7.239,7.921 6.383,8.601 6.676,9.654 5.765,9.05 4.854,9.654 5.146,8.601 4.29,7.921 5.383,7.874", fill: "#facc15" },
    { t: "polygon", points: "8.4,4.215 8.782,5.239 9.874,5.286 9.018,5.965 9.311,7.019 8.4,6.415 7.489,7.019 7.782,5.965 6.926,5.286 8.018,5.239", fill: "#facc15" },
  ] },
  { id: 14, name: "Wheat sheaf", shapes: [
    { t: "line", x1: 12, y1: 21, x2: 12, y2: 10, stroke: "#92400e", sw: 1.6 },
    { t: "path", d: "M12 10c-2.2-1.8-2.8-4.5-1.6-7.2 2.2 1.6 2.6 4.2 1.6 7.2z", fill: "#eab308" },
    { t: "path", d: "M12 12.5c-3-1.2-4.4-3.8-3.6-6.8 2.4 1.2 3.4 3.6 3.6 6.8z", fill: "#facc15" },
    { t: "path", d: "M12 12.5c3-1.2 4.4-3.8 3.6-6.8-2.4 1.2-3.4 3.6-3.6 6.8z", fill: "#facc15" },
    { t: "path", d: "M12 14.5c-2.4-.6-3.6-2.4-3.2-4.5 1.8.8 2.8 2.4 3.2 4.5z", fill: "#eab308" },
    { t: "path", d: "M12 14.5c2.4-.6 3.6-2.4 3.2-4.5-1.8.8-2.8 2.4-3.2 4.5z", fill: "#eab308" },
    { t: "rect", x: 9.2, y: 16.2, w: 5.6, h: 1.5, rx: 0.4, fill: "#92400e" },
  ] },
  { id: 15, name: "Factory with smokestacks", shapes: [
    { t: "path", d: "M2 20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8l-7 5V8l-7 5V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z", fill: "none", stroke: "#4b5563", sw: 1.75 },
    { t: "path", d: "M17 18h1", fill: "none", stroke: "#4b5563", sw: 1.75 },
    { t: "path", d: "M12 18h1", fill: "none", stroke: "#4b5563", sw: 1.75 },
    { t: "path", d: "M7 18h1", fill: "none", stroke: "#4b5563", sw: 1.75 },
  ] },
  { id: 16, name: "Gear/cog", shapes: [
    { t: "path", d: "M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M12 2v2", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M12 22v-2", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m17 20.66-1-1.73", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M11 10.27 7 3.34", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m20.66 17-1.73-1", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m3.34 7 1.73 1", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M14 12h8", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "M2 12h2", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m20.66 7-1.73 1", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m3.34 17 1.73-1", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m17 3.34-1 1.73", fill: "none", stroke: "#6b7280", sw: 1.75 },
    { t: "path", d: "m11 13.73-4 6.93", fill: "none", stroke: "#6b7280", sw: 1.75 },
  ] },
  { id: 17, name: "Dollar sign", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 10, fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "M12 18V6", fill: "none", stroke: "#16a34a", sw: 1.75 },
  ] },
  { id: 18, name: "Stacked coins", shapes: [
    { t: "circle", cx: 8, cy: 8, r: 6, fill: "none", stroke: "#eab308", sw: 1.75 },
    { t: "path", d: "M18.09 10.37A6 6 0 1 1 10.34 18", fill: "none", stroke: "#eab308", sw: 1.75 },
    { t: "path", d: "M7 6h1v4", fill: "none", stroke: "#eab308", sw: 1.75 },
    { t: "path", d: "m16.71 13.88.7.71-2.82 2.82", fill: "none", stroke: "#eab308", sw: 1.75 },
  ] },
  { id: 19, name: "Padlock", shapes: [
    { t: "rect", x: 3, y: 11, w: 18, h: 11, rx: 2, fill: "none", stroke: "#4b5563", sw: 1.75 },
    { t: "path", d: "M7 11V7a5 5 0 0 1 10 0v4", fill: "none", stroke: "#4b5563", sw: 1.75 },
  ] },
  { id: 20, name: "Recycling arrows", shapes: [
    { t: "path", d: "M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "m14 16-3 3 3 3", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "M8.293 13.596 7.196 9.5 3.1 10.598", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843", fill: "none", stroke: "#16a34a", sw: 1.75 },
    { t: "path", d: "m13.378 9.633 4.096 1.098 1.097-4.096", fill: "none", stroke: "#16a34a", sw: 1.75 },
  ] },
  { id: 21, name: "Progress pride flag", assetUrl: prideFlagUrl, shapes: [] },
  { id: 22, name: "Mars Male symbol", shapes: [
    { t: "circle", cx: 10, cy: 14, r: 5.5, fill: "none", stroke: "#2563eb", sw: 1.9 },
    { t: "line", x1: 13.9, y1: 10.1, x2: 19.5, y2: 4.5, stroke: "#2563eb", sw: 1.9 },
    { t: "line", x1: 15.2, y1: 4.5, x2: 19.5, y2: 4.5, stroke: "#2563eb", sw: 1.9 },
    { t: "line", x1: 19.5, y1: 4.5, x2: 19.5, y2: 8.8, stroke: "#2563eb", sw: 1.9 },
  ] },
  { id: 23, name: "Mars Female Symbol", shapes: [
    { t: "circle", cx: 12, cy: 9, r: 5.5, fill: "none", stroke: "#db2777", sw: 1.9 },
    { t: "line", x1: 12, y1: 14.5, x2: 12, y2: 21, stroke: "#db2777", sw: 1.9 },
    { t: "line", x1: 8.5, y1: 18, x2: 15.5, y2: 18, stroke: "#db2777", sw: 1.9 },
  ] },
  { id: 24, name: "UN Emblem", shapes: [
    { t: "circle", cx: 12, cy: 11.2, r: 10.2, fill: "#5b92e5" },
    { t: "circle", cx: 12, cy: 10.8, r: 6.6, fill: "none", stroke: "#f8fafc", sw: 0.7 },
    { t: "circle", cx: 12, cy: 10.8, r: 3.8, fill: "none", stroke: "#f8fafc", sw: 0.65 },
    { t: "circle", cx: 12, cy: 10.8, r: 1.1, fill: "#f8fafc" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(0 12 10.8)", key: "m0" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(30 12 10.8)", key: "m1" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(60 12 10.8)", key: "m2" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(90 12 10.8)", key: "m3" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(120 12 10.8)", key: "m4" },
    { t: "line", x1: 12, y1: 4.2, x2: 12, y2: 17.4, stroke: "#f8fafc", sw: 0.55, transform: "rotate(150 12 10.8)", key: "m5" },
    { t: "path", d: "M5.8 19.2c-1.8-2.4-2.2-5.6-1-8.4", stroke: "#f8fafc", sw: 1.05, fill: "none" },
    { t: "path", d: "M18.2 19.2c1.8-2.4 2.2-5.6 1-8.4", stroke: "#f8fafc", sw: 1.05, fill: "none" },
    { t: "ellipse", cx: 5.6, cy: 18.4, rx: 1.2, ry: 0.55, fill: "#f8fafc", transform: "rotate(-35 5.6 18.4)" },
    { t: "ellipse", cx: 5.1, cy: 15.6, rx: 1.2, ry: 0.55, fill: "#f8fafc", transform: "rotate(-20 5.1 15.6)" },
    { t: "ellipse", cx: 5, cy: 12.8, rx: 1.15, ry: 0.5, fill: "#f8fafc", transform: "rotate(-5 5 12.8)" },
    { t: "ellipse", cx: 5.5, cy: 10.4, rx: 1.1, ry: 0.5, fill: "#f8fafc", transform: "rotate(12 5.5 10.4)" },
    { t: "ellipse", cx: 18.4, cy: 18.4, rx: 1.2, ry: 0.55, fill: "#f8fafc", transform: "rotate(35 18.4 18.4)" },
    { t: "ellipse", cx: 18.9, cy: 15.6, rx: 1.2, ry: 0.55, fill: "#f8fafc", transform: "rotate(20 18.9 15.6)" },
    { t: "ellipse", cx: 19, cy: 12.8, rx: 1.15, ry: 0.5, fill: "#f8fafc", transform: "rotate(5 19 12.8)" },
    { t: "ellipse", cx: 18.5, cy: 10.4, rx: 1.1, ry: 0.5, fill: "#f8fafc", transform: "rotate(-12 18.5 10.4)" },
  ] },
  { id: 25, name: "Compass rose", shapes: [
    { t: "path", d: "m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z", fill: "none", stroke: "#374151", sw: 1.75 },
    { t: "circle", cx: 12, cy: 12, r: 10, fill: "none", stroke: "#374151", sw: 1.75 },
  ] },
  { id: 26, name: "Radar/spider-chart outline", shapes: [
    { t: "polygon", points: "12,3 20.2,9 17,19.5 7,19.5 3.8,9", fill: "none", stroke: "#059669", sw: 1.25 },
    { t: "polygon", points: "12,7 16.4,10.4 14.6,16.2 9.4,16.2 7.6,10.4", fill: "none", stroke: "#059669", sw: 1.15 },
    { t: "polygon", points: "12,10.2 14.2,11.8 13.3,14.6 10.7,14.6 9.8,11.8", fill: "#a7f3d0", stroke: "#059669", sw: 1 },
    { t: "line", x1: 12, y1: 3, x2: 12, y2: 12, stroke: "#059669", sw: 0.85 },
    { t: "line", x1: 20.2, y1: 9, x2: 12, y2: 12, stroke: "#059669", sw: 0.85 },
    { t: "line", x1: 17, y1: 19.5, x2: 12, y2: 12, stroke: "#059669", sw: 0.85 },
    { t: "line", x1: 7, y1: 19.5, x2: 12, y2: 12, stroke: "#059669", sw: 0.85 },
    { t: "line", x1: 3.8, y1: 9, x2: 12, y2: 12, stroke: "#059669", sw: 0.85 },
  ] },
  { id: 27, name: "Yin-yang", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 10, fill: "#111827" },
    { t: "path", d: "M12 2a10 10 0 0 1 0 20 5 5 0 0 1 0-10 5 5 0 0 0 0-10z", fill: "#f8fafc" },
    { t: "circle", cx: 12, cy: 7, r: 1.7, fill: "#f8fafc" },
    { t: "circle", cx: 12, cy: 17, r: 1.7, fill: "#111827" },
  ] },
  { id: 28, name: "Brain outline", shapes: [
    { t: "path", d: "M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M17.599 6.5a3 3 0 0 0 .399-1.375", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M6.003 5.125A3 3 0 0 0 6.401 6.5", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M3.477 10.896a4 4 0 0 1 .585-.396", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M19.938 10.5a4 4 0 0 1 .585.396", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M6 18a4 4 0 0 1-1.967-.516", fill: "none", stroke: "#ec4899", sw: 1.75 },
    { t: "path", d: "M19.967 17.484A4 4 0 0 1 18 18", fill: "none", stroke: "#ec4899", sw: 1.75 },
  ] },
  { id: 29, name: "Puzzle piece", shapes: [
    { t: "path", d: "M15.39 4.39a1 1 0 0 0 1.68-.474 2.5 2.5 0 1 1 3.014 3.015 1 1 0 0 0-.474 1.68l1.683 1.682a2.414 2.414 0 0 1 0 3.414L19.61 15.39a1 1 0 0 1-1.68-.474 2.5 2.5 0 1 0-3.014 3.015 1 1 0 0 1 .474 1.68l-1.683 1.682a2.414 2.414 0 0 1-3.414 0L8.61 19.61a1 1 0 0 0-1.68.474 2.5 2.5 0 1 1-3.014-3.015 1 1 0 0 0 .474-1.68l-1.683-1.682a2.414 2.414 0 0 1 0-3.414L4.39 8.61a1 1 0 0 1 1.68.474 2.5 2.5 0 1 0 3.014-3.015 1 1 0 0 1-.474-1.68l1.683-1.682a2.414 2.414 0 0 1 3.414 0z", fill: "none", stroke: "#f97316", sw: 1.75 },
  ] },
  { id: 31, name: "Infinity symbol", shapes: [
    { t: "path", d: "M12 12c-2-2.67-4-4-6-4a4 4 0 1 0 0 8c2 0 4-1.33 6-4Zm0 0c2 2.67 4 4 6 4a4 4 0 0 0 0-8c-2 0-4 1.33-6 4Z", fill: "none", stroke: "#4338ca", sw: 1.75 },
  ] },
  { id: 32, name: "Labyrinth/maze", shapes: [
    { t: "rect", x: 3.5, y: 3.5, w: 17, h: 17, fill: "none", stroke: "#57534e", sw: 1.5 },
    { t: "rect", x: 6.5, y: 6.5, w: 11, h: 11, fill: "none", stroke: "#57534e", sw: 1.5 },
    { t: "rect", x: 9.5, y: 9.5, w: 5, h: 5, fill: "none", stroke: "#57534e", sw: 1.5 },
    { t: "line", x1: 12, y1: 3.5, x2: 12, y2: 6.5, stroke: "#f5f5f4", sw: 2 },
    { t: "line", x1: 17.5, y1: 12, x2: 20.5, y2: 12, stroke: "#f5f5f4", sw: 2 },
    { t: "line", x1: 12, y1: 14.5, x2: 12, y2: 17.5, stroke: "#f5f5f4", sw: 2 },
  ] },
  { id: 33, name: "Om symbol", assetUrl: omSymbolUrl, shapes: [] },
  { id: 34, name: "Lotus flower", shapes: [
    { t: "path", d: "M12 20c0-5-2.2-9.5 0-14 2.2 4.5 0 9 0 14z", fill: "#f9a8d4" },
    { t: "path", d: "M12 20c-3.2-4-5.5-7.5-4.2-12.2 3 2.8 3.8 7 4.2 12.2z", fill: "#f472b6" },
    { t: "path", d: "M12 20c3.2-4 5.5-7.5 4.2-12.2-3 2.8-3.8 7-4.2 12.2z", fill: "#f472b6" },
    { t: "path", d: "M12 20c-5-2.8-7.5-6-7-10.5 3.5 1.8 5.8 5.5 7 10.5z", fill: "#ec4899" },
    { t: "path", d: "M12 20c5-2.8 7.5-6 7-10.5-3.5 1.8-5.8 5.5-7 10.5z", fill: "#ec4899" },
    { t: "circle", cx: 12, cy: 18.2, r: 1.4, fill: "#fce7f3" },
  ] },
  { id: 35, name: "Crescent moon and star", assetUrl: starCrescentUrl, shapes: [] },
  { id: 36, name: "Cross", shapes: [
    { t: "rect", x: 10.2, y: 2.8, w: 3.6, h: 18.4, rx: 0.6, fill: "#78716c" },
    { t: "rect", x: 4.2, y: 7.5, w: 15.6, h: 3.6, rx: 0.6, fill: "#78716c" },
  ] },
  { id: 37, name: "Star of David", shapes: [
    { t: "polygon", points: "12,3.2 20.2,17.5 3.8,17.5", fill: "none", stroke: "#2563eb", sw: 1.7 },
    { t: "polygon", points: "12,20.8 3.8,6.5 20.2,6.5", fill: "none", stroke: "#2563eb", sw: 1.7 },
  ] },
  { id: 38, name: "Dharma wheel", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 9.2, fill: "none", stroke: "#b45309", sw: 1.7 },
    { t: "circle", cx: 12, cy: 12, r: 6.2, fill: "none", stroke: "#b45309", sw: 1.1 },
    { t: "circle", cx: 12, cy: 12, r: 2.1, fill: "#b45309" },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(0 12 12)", key: 0 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(45 12 12)", key: 1 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(90 12 12)", key: 2 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(135 12 12)", key: 3 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(180 12 12)", key: 4 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(225 12 12)", key: 5 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(270 12 12)", key: 6 },
    { t: "line", x1: 12, y1: 12, x2: 12, y2: 3.2, stroke: "#b45309", sw: 1.25, transform: "rotate(315 12 12)", key: 7 },
  ] },
  { id: 39, name: "Heart", shapes: [
    { t: "path", d: "M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z", fill: "#e11d48" },
  ] },
  { id: 40, name: "Interlocking rings", shapes: [
    { t: "circle", cx: 6.2, cy: 9.2, r: 3.6, fill: "none", stroke: "#2563eb", sw: 1.5 },
    { t: "circle", cx: 12, cy: 9.2, r: 3.6, fill: "none", stroke: "#111827", sw: 1.5 },
    { t: "circle", cx: 17.8, cy: 9.2, r: 3.6, fill: "none", stroke: "#dc2626", sw: 1.5 },
    { t: "circle", cx: 9.1, cy: 12.8, r: 3.6, fill: "none", stroke: "#eab308", sw: 1.5 },
    { t: "circle", cx: 14.9, cy: 12.8, r: 3.6, fill: "none", stroke: "#16a34a", sw: 1.5 },
  ] },
  { id: 41, name: "Zodiac wheel", shapes: [
    { t: "circle", cx: 12, cy: 12, r: 9.5, fill: "none", stroke: "#7c3aed", sw: 1.5 },
    { t: "circle", cx: 12, cy: 12, r: 6.5, fill: "none", stroke: "#7c3aed", sw: 1.1 },
    { t: "circle", cx: 12, cy: 12, r: 1.4, fill: "#7c3aed" },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(0 12 12)", key: 0 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(30 12 12)", key: 1 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(60 12 12)", key: 2 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(90 12 12)", key: 3 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(120 12 12)", key: 4 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(150 12 12)", key: 5 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(180 12 12)", key: 6 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(210 12 12)", key: 7 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(240 12 12)", key: 8 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(270 12 12)", key: 9 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(300 12 12)", key: 10 },
    { t: "line", x1: 12, y1: 2.8, x2: 12, y2: 5.2, stroke: "#7c3aed", sw: 1.15, transform: "rotate(330 12 12)", key: 11 },
  ] },
  { id: 42, name: "Crystal ball", shapes: [
    { t: "circle", cx: 12, cy: 10.5, r: 7.8, fill: "#c4b5fd" },
    { t: "ellipse", cx: 9.4, cy: 7.6, rx: 2.4, ry: 1.5, fill: "#ede9fe" },
    { t: "path", d: "M7.2 17.8c1.2 1.4 2.8 2.2 4.8 2.2s3.6-.8 4.8-2.2", stroke: "#7c3aed", sw: 1.1, fill: "none" },
    { t: "rect", x: 7.5, y: 19.2, w: 9, h: 2, rx: 0.6, fill: "#57534e" },
  ] },
  { id: 43, name: "Briefcase", shapes: [
    { t: "path", d: "M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16", fill: "none", stroke: "#92400e", sw: 1.75 },
    { t: "rect", x: 2, y: 6, w: 20, h: 14, rx: 2, fill: "none", stroke: "#92400e", sw: 1.75 },
  ] },
  { id: 44, name: "Artist's palette", shapes: [
    { t: "circle", cx: 13.5, cy: 6.5, r: 0.5, fill: "none", stroke: "#78350f", sw: 1.75 },
    { t: "circle", cx: 17.5, cy: 10.5, r: 0.5, fill: "none", stroke: "#78350f", sw: 1.75 },
    { t: "circle", cx: 8.5, cy: 7.5, r: 0.5, fill: "none", stroke: "#78350f", sw: 1.75 },
    { t: "circle", cx: 6.5, cy: 12.5, r: 0.5, fill: "none", stroke: "#78350f", sw: 1.75 },
    { t: "path", d: "M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z", fill: "none", stroke: "#78350f", sw: 1.75 },
    { t: "circle", cx: 9, cy: 10, r: 1.2, fill: "#dc2626" },
    { t: "circle", cx: 12.5, cy: 8, r: 1.2, fill: "#2563eb" },
    { t: "circle", cx: 15.5, cy: 10.5, r: 1.2, fill: "#16a34a" },
    { t: "circle", cx: 11, cy: 13.5, r: 1.2, fill: "#eab308" },
  ] },
];
